name: CI


permissions:
  contents: write


on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  cpm-path: .cpm
  cpm-key: waterwall-1.1.0-cpm

jobs:
  android:
    strategy:
      fail-fast: false
      matrix:
        arch: [armeabi-v7a, arm64-v8a, x86, x86_64]
    name: android-${{ matrix.arch }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ env.cpm-path }}
          key: ${{ env.cpm-key }}
          enableCrossOsArchive: true
      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build ccache
      - name: Configure CMake
        run: >
          cmake -B build -G Ninja
          -DANDROID_ABI=${{ matrix.arch }}
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
          -DCPM_SOURCE_CACHE=${{ env.cpm-path }}
          -DOPENSSL_CONFIGURE_VERBOSE=ON
      
      - name: Build
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Waterwall_android_${{ matrix.arch }}
          path: ${{ github.workspace }}/build/Waterwall

      - name: Show ccache statistics
        run: ccache -sv

  bsd:
    strategy:
      fail-fast: false
      matrix:
        # preset: [freebsd, netbsd, openbsd]
        # arch: [arm64, x86_64]
        preset: [freebsd]
        arch: [x86_64]
        include:
          - preset: freebsd
            version: "14.2"
            install: sudo pkg install -y cmake perl5 git
          # - preset: netbsd
          #   version: "10.1"
          #   install: sudo pkgin -y install cmake perl git
          # - preset: openbsd
          #   version: "7.6"
          #   install: sudo pkg_add cmake git
            
    name: ${{ matrix.preset }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ env.cpm-path }}
          key: ${{ env.cpm-key }}
          enableCrossOsArchive: true
         
      - uses: cross-platform-actions/action@master
        with:
          operating_system: ${{ matrix.preset }}
          architecture: ${{ matrix.arch }}
          version: ${{ matrix.version }}
          run: |
            ${{ matrix.install }}
            cmake -B build -G Ninja                \
              -DCPM_SOURCE_CACHE=${{ env.cpm-path }} \
              -DOPENSSL_CONFIGURE_VERBOSE=ON

      - uses: cross-platform-actions/action@master
        with:
          operating_system: ${{ matrix.preset }}
          architecture: ${{ matrix.arch }}
          version: ${{ matrix.version }}
          run: cmake --build build  

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Waterwall_BSD_${{ matrix.preset }}_${{ matrix.arch }}
          path: ${{ github.workspace }}/build/Waterwall

  ios:
    strategy:
      fail-fast: false
      matrix:
        target: [ios, ios_sim]
    name: ${{ matrix.target }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ env.cpm-path }}
          key: ${{ env.cpm-key }}
          enableCrossOsArchive: true
      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install ccache

      - name: Configure CMake
        run: >
          cmake -B build -G Xcode
          -DCMAKE_TOOLCHAIN_FILE=ww/cmake/toolchain/${{ matrix.target }}.cmake
          -DCPM_SOURCE_CACHE=${{ env.cpm-path }}
          -DOPENSSL_CONFIGURE_VERBOSE=ON

      - name: Build
        run: cmake --build build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Waterwall_${{ matrix.target }}
          path: ${{ matrix.target == 'ios_sim' && format('{0}/build/Debug-iphonesimulator/Waterwall.app/', github.workspace) || format('{0}/build/Debug-iphoneos/Waterwall.app/', github.workspace) }}
      - name: Show ccache statistics
        run: ccache -sv

  linux:
    strategy:
      fail-fast: false
      matrix:
        cc: [clang, gcc]
    name: linux-${{ matrix.cc }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ env.cpm-path }}
          key: ${{ env.cpm-key }}
          enableCrossOsArchive: true
      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build ccache
      - name: Configure CMake
        run: >
          cmake -B build -G Ninja
          -DCMAKE_C_COMPILER=${{ matrix.cc }}
          -DCPM_SOURCE_CACHE=${{ env.cpm-path }}
          -DOPENSSL_CONFIGURE_VERBOSE=ON
      - name: Build
        run: cmake --build build --config Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Waterwall_linux_x64_${{ matrix.cc }}
          path: ${{ github.workspace }}/build/Waterwall
      - name: Show ccache statistics
        run: ccache -sv

  linux-old-cpu:
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc]
    name: linux-old-cpu-${{ matrix.cc }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ env.cpm-path }}
          key: ${{ env.cpm-key }}
          enableCrossOsArchive: true
      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build ccache
      - name: Configure CMake
        run: >
          cmake --preset linux-gcc-old-cpu
      - name: Build
        run: cmake --build build --preset linux-gcc-old-cpu
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Waterwall_linux_X64_${{ matrix.cc }}_old_cpus
          path: ${{ github.workspace }}/build/linux-gcc-old-cpu/Release/Waterwall
      - name: Show ccache statistics
        run: ccache -sv
  
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ env.cpm-path }}
          key: ${{ env.cpm-key }}
          enableCrossOsArchive: true
      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install ccache
      - name: Configure CMake
        run: >
          cmake -B build
          -DCPM_SOURCE_CACHE=${{ env.cpm-path }}
          -DOPENSSL_CONFIGURE_VERBOSE=ON

      - name: Build
        run: cmake --build  build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Waterwall_${{ runner.os }}
          path: ${{ github.workspace }}/build/Waterwall

      - name: Show ccache statistics
        run: ccache -sv

  msys2:
    strategy:
      fail-fast: false
      matrix:
        preset: [CLANG64, MINGW32, MINGW64, UCRT64]
    name: msys2-${{ matrix.preset }}
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ env.cpm-path }}
          key: ${{ env.cpm-key }}
          enableCrossOsArchive: true
      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          choco install -y jom nasm ccache
          echo "PATH=$ENV:PATH;C:\Program Files\NASM" >> $ENV:GITHUB_ENV

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.preset }}
          update: true
          pacboy: >-
            ccache:p
            cmake:p
            gcc:p
            make:p
            ninja:p
      
      - name: Configure CMake
        shell: msys2 {0}
        run: >
          cmake -B build -G Ninja
          -DCPM_SOURCE_CACHE=${{ env.cpm-path }}
          -DOPENSSL_CONFIGURE_VERBOSE=ON

      - name: Build
        run: cmake --build  build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Waterwall_windows_MSYS2_${{ matrix.preset }}
          path: ${{ github.workspace }}/build/Waterwall.exe

      - name: Show ccache statistics
        run: ccache -sv

  windows:
    strategy:
      fail-fast: false
      matrix:
        arch: [ARM64, Win32, x64]
    name: windows-${{ matrix.arch }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ env.cpm-path }}
          key: ${{ env.cpm-key }}
          enableCrossOsArchive: true
      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install -y jom nasm ccache
          echo "PATH=$ENV:PATH;C:\Program Files\NASM" >> $ENV:GITHUB_ENV

      - name: Configure CMake
        run: >
          cmake -B build -A ${{ matrix.arch }}
          -DCPM_SOURCE_CACHE="${{ env.cpm-path }}"
          -DOPENSSL_CONFIGURE_OPTIONS=no-asm
          -DOPENSSL_CONFIGURE_VERBOSE=ON

      - name: Build
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Waterwall_windows_${{ matrix.arch }}
          path: ${{ github.workspace }}/build/Release/Waterwall.exe

      - name: Show ccache statistics
        run: ccache -sv

  linux-arm:
    name: linux-arm64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ env.cpm-path }}
          key: ${{ env.cpm-key }}
          enableCrossOsArchive: true
      - name: Install dependencies and cross-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build ccache gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: Configure CMake for ARM64
        run: >
          cmake -B build -G Ninja \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
            -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
            -DCPM_SOURCE_CACHE=${{ env.cpm-path }} \
            -DOPENSSL_CONFIGURE_VERBOSE=ON
      - name: Build
        run: cmake --build build --config Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Waterwall_linux_arm64
          path: ${{ github.workspace }}/build/Waterwall
      - name: Show ccache statistics
        run: ccache -sv

  linux-arm-old-cpu:
    name: linux-arm64-old-cpu
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ env.cpm-path }}
          key: ${{ env.cpm-key }}
          enableCrossOsArchive: true
      - name: Install dependencies and cross-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build ccache gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: Configure CMake for ARM64
        run: >
          cmake -B build -G Ninja \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
            -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
            -DCPM_SOURCE_CACHE=${{ env.cpm-path }} \
            -DOPENSSL_CONFIGURE_VERBOSE=ON \
            -DDISABLE_AVX=1 

      - name: Build
        run: cmake --build build --config Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Waterwall_linux_arm64_old_cpu
          path: ${{ github.workspace }}/build/Waterwall
      - name: Show ccache statistics
        run: ccache -sv

  release:
      needs:
        # - android
        # - bsd
        # - ios
        - linux
        - linux-arm
        - linux-arm-old-cpu
        # - macos
        - msys2
        - windows
        - linux-old-cpu

      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Configure CMake
          run: |
            cmake -B build

        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            path: downloaded_artifacts

        - name: Extract version
          run: |
            VERSION=$(cat ww/cmake/version.txt)
            echo "Project version: $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_ENV


        - name: Check if tag exists
          id: check_tag
          run: |
            git fetch --tags
            if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
              echo "exists=true" >> $GITHUB_OUTPUT
            else
              echo "exists=false" >> $GITHUB_OUTPUT
            fi

        - name: Create Git Tag
          if: steps.check_tag.outputs.exists == 'false'
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag -a "v${{ env.VERSION }}" -m "Release v${{ env.VERSION }}"
            git push origin "v${{ env.VERSION }}"

        - name: Zip release files
          if: steps.check_tag.outputs.exists == 'false'
          run: |
            ls -ln downloaded_artifacts
            mkdir -p zipped_artifacts
            for dir in downloaded_artifacts/*; do
              if [ -d "$dir" ]; then
                base=$(basename "$dir")
                cd "$dir" && zip -r "../../zipped_artifacts/${base}.zip" .
                cd ../..
              fi
            done


        - name: Create GitHub Release
          if: steps.check_tag.outputs.exists == 'false'
          uses: softprops/action-gh-release@v2
          with:
            tag_name: v${{ env.VERSION }}
            files: |
              zipped_artifacts/*.zip



